version: "3.9"

services:
  qdrant:
    container_name: qdrant-db
    image: qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - $(PWD)/qdrant_storage:/qdrant/storage:z