services:
  main-tender-bot:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      mongodb_host: mongodb
    env_file:
      - .env
    ports:
      - "8000"
    networks:
      tender-bot:
    depends_on:
      - mongodb
    labels:
      - "traefik.http.routers.main.rule=Host(`app.localhost`)"

  mongodb:
    container_name: mongodb-tender-bot
    image: mongo
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    volumes:
      - mongodb-data:/data/db
    networks:
      tender-bot:

  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.1
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - main-tender-bot
    networks:
      tender-bot:

networks:
  tender-bot:
    external: true

volumes:
  mongodb-data:
