version: "3.9"

services:
  rag:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rag.rule=Host(`rag.localhost`)"
      - "traefik.http.services.rag.loadbalancer.server.port=8000"
    networks:
      tender-bot:

networks:
    tender-bot:
        external: true